## schema for yamale - see https://github.com/23andMe/Yamale

webserver: include('Webserver', strict=True)
imageserver: include('ImageServer', strict=True)
crawlers: list(include('Crawler', strict=True), min=1)
logging: include('Logging', strict=True, required=False, none=False)


---
Logging:
  level: enum('CRITICAL', 'ERROR', 'WARNING', 'INFO', 'DEBUG', required=False, none=False)
---
Webserver:
  hostname: str(min=1)
  port: int(min=1, max=65535)
  proxy: include('Webserver_Proxy', strict=True, required=False, none=False)
Webserver_Proxy:
  x_for: int(min=0)
  x_proto: int(min=0)
  x_host: int(min=0)
  x_port: int(min=0)
  x_prefix: int(min=0)
---
ImageServer:
  crawler_upkeep: int(min=10)
---
Crawler:
  type: str(min=1)
  weight: num(min=0.0001, required=False, none=False)
  config: map(required=False, none=False)
