webserver: include('Webserver', strict=True)
server: include('Server', strict=True)
crawlers: list(include('Crawler', strict=True), min=1)
---
Webserver:
  host: str(min=1)
  port: int(min=1, max=65535)
---
Server:
  crawler_upkeep: int(min=10)
---
Crawler:
  type: str(min=1)
  weight: num(min=0.0001, required=False)
  config: map()
