name: "Test"

on:
  push:
  pull_request:

jobs:
  test:
    name: Testing
    strategy:
      matrix:
        os: ['ubuntu-latest']
        pyhon: ['3.5', '3.6', '3.7', '3.8']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.pyhon_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.pyhon }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade setuptools tox
      - name: Test nichtparasoup
        run: |
          python3 -m tox
      - name: "Test examples::nichtparasoup-imagecrawler-plugin"
        run: |
          python3 -m tox -c examples/nichtparasoup-imagecrawler-plugin/
